"""Stable probabilistic namespace for conformal and calibration models."""

from .forecasting.probabilistic import (
    ConformalCalibrator,
    ConformalInterval,
    ConformalIntervalRegressor,
    DistributionalForecastResult,
    ForecastConformalCalibrator,
    QuantileCartoBoostRegressor,
    QuantileForecast,
    SpatialConformalRegressor,
    benchmark_calibration_report_fields,
    crps_approximation,
    group_conformal_residual_quantiles,
    interval_coverage,
    mean_interval_width,
    nearest_conformal_residual_quantiles,
    pinball_loss,
    pit_bins,
    rank_probability_score,
    repair_non_crossing_quantiles,
    weighted_conformal_residual_quantile,
    weighted_interval_score,
)

__all__ = [
    "ConformalCalibrator",
    "ConformalInterval",
    "ConformalIntervalRegressor",
    "DistributionalForecastResult",
    "ForecastConformalCalibrator",
    "QuantileCartoBoostRegressor",
    "QuantileForecast",
    "SpatialConformalRegressor",
    "benchmark_calibration_report_fields",
    "crps_approximation",
    "group_conformal_residual_quantiles",
    "interval_coverage",
    "mean_interval_width",
    "nearest_conformal_residual_quantiles",
    "pinball_loss",
    "pit_bins",
    "rank_probability_score",
    "repair_non_crossing_quantiles",
    "weighted_conformal_residual_quantile",
    "weighted_interval_score",
]
