import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Get Started',
      collapsed: false,
      items: [
        'index',
        'installation',
        'getting-started',
        'migration-v0.3',
        'user-guide/model-types',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Boosting Models',
          items: [
            'user-guide/boosting-models/index',
            'user-guide/boosting-models/cartoboost-regressor',
            'user-guide/boosting-models/cartoboost-classifier',
            'user-guide/boosting-models/cartoboost-ranker',
            'user-guide/python-estimator',
            'user-guide/categorical-features',
            'user-guide/spatial-cv-best-practices',
            'user-guide/geo-evaluation-standard',
            'user-guide/spatial-econometrics',
            'user-guide/geostatistics-models',
            'user-guide/parameters',
            'objectives',
            'constraints',
            'spatial_modeling',
            'feature_schema',
            'sparse_features',
            'shap',
            'model_artifact',
          ],
        },
        {
          type: 'category',
          label: 'Forecasting',
          collapsed: false,
          items: [
            'forecasting',
            'user-guide/forecasting-models/index',
            'user-guide/forecasting-models/auto-forecaster',
            'user-guide/forecasting-models/naive-seasonal',
            'user-guide/forecasting-models/theta',
            'user-guide/forecasting-models/ets',
            'user-guide/forecasting-models/arima',
            'user-guide/forecasting-models/kalman',
            'user-guide/forecasting-models/piecewise-linear-seasonal',
            'user-guide/forecasting-models/kriging',
            'user-guide/forecasting-models/spatial-piecewise-kriging',
            'user-guide/forecasting-models/cartoboost-lag',
            'user-guide/forecasting-models/graph-spatiotemporal',
            'user-guide/forecasting-models/probabilistic-conformal',
            'user-guide/forecasting-models/beats-hits',
            'user-guide/forecasting-models/neural-panel',
            'user-guide/forecasting-models/auto-stats-bank',
            'user-guide/forecasting-models/intermittent-demand',
            'user-guide/forecasting-models/croston',
            'user-guide/forecasting-models/sba',
            'user-guide/forecasting-models/tsb',
            'user-guide/forecasting-models/ensembles',
          ],
        },
        {
          type: 'category',
          label: 'Neural Models',
          items: [
            'user-guide/neural-models/index',
            'user-guide/neural-models/cartoboost-neural-embedding',
            'user-guide/neural-models/cartoboost-neural-embedding-features',
            'user-guide/neural-models/cartoboost-neural-embedding-regressor',
          ],
        },
        {
          type: 'category',
          label: 'Deep Models',
          items: [
            'user-guide/deep-models',
            'user-guide/deep-models/cartoboost-choice-set-transformer',
            'user-guide/deep-models/cartoboost-conditional-flow-distribution-head',
            'user-guide/deep-models/cartoboost-constrained-decision-optimizer',
            'user-guide/deep-models/cartoboost-directional-pair-forecaster',
            'user-guide/deep-models/cartoboost-event-outcome-model',
            'user-guide/deep-models/cartoboost-geotemporal-diffusion-scenario-model',
            'user-guide/deep-models/cartoboost-graph-neural-operator',
            'user-guide/deep-models/cartoboost-inverted-temporal-transformer',
            'user-guide/deep-models/cartoboost-propagation-delay-graph-forecaster',
            'user-guide/deep-models/cartoboost-regime-moe-forecaster',
            'user-guide/deep-models/cartoboost-response-curve-model',
            'user-guide/deep-models/cartoboost-service-time-residual-model',
            'user-guide/deep-models/cartoboost-spatiotemporal-graph-forecaster',
          ],
        },
        {
          type: 'category',
          label: 'Graph Models',
          items: [
            'user-guide/graph-models/index',
            'user-guide/graph-models/cartoboost-node2vec',
            'user-guide/graph-models/cartoboost-graphsage',
            'user-guide/graph-models/cartoboost-hetero-graphsage',
            'user-guide/graph-models/cartoboost-hinsage',
          ],
        },
        'general_utilities',
      ],
    },
    {
      type: 'link',
      label: 'Modeling Lab',
      href: '/modeling-lab',
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [
        'reference/python-api',
        'reference/cli',
        'feature_catalog',
        'graph-features',
        'neural-features',
      ],
    },
    {
      type: 'category',
      label: 'Benchmarks',
      collapsed: false,
      items: [
        'benchmarks/index',
        'benchmarks/model-suite',
        'benchmarks/methodology',
        'benchmarks/nyc-taxi',
        'benchmarks/nyc-taxi-path-c',
        'benchmarks/forecasting',
        'benchmarks/deep-claims',
        'benchmarks/taxi-zone',
        'benchmarks/lane-level',
        'benchmarks/neural-embedding-benchmark-latest',
      ],
    },
  ],
};

export default sidebars;
