from __future__ import annotations

import json
from pathlib import Path

from cartoboost.capabilities import capability_table

ROOT = Path(__file__).resolve().parents[1]
ASSET_PATH = ROOT / "docs" / "assets" / "capabilities" / "model_capabilities.json"
DOC_PATH = ROOT / "docs" / "reference" / "capability-matrix.md"
LEGACY_DOC_PATH = ROOT / "docs" / "reference" / "model-capabilities.md"


def main() -> None:
    rows = capability_table()
    ASSET_PATH.parent.mkdir(parents=True, exist_ok=True)
    ASSET_PATH.write_text(json.dumps(rows, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    table = [
        "# Model Capability Table",
        "",
        "Generated by `scripts/generate_capability_table.py`.",
        "",
        (
            "| Class | Architecture | Capability tier | Backend | Parameters | "
            "Native core | Evidence | Status |"
        ),
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for row in rows:
        table.append(
            "| {class_name} | {architecture} | {capability_tier} | {implementation_backend} | "
            "{trainable_parameters} | {uses_native_core} | {benchmark_evidence} | "
            "{experimental_status} |".format(**row)
        )
    text = "\n".join(table) + "\n"
    DOC_PATH.write_text(text, encoding="utf-8")
    LEGACY_DOC_PATH.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
